const ActionTypes = {
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  GET_IMAGES: 'GET_IMAGES',
  GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
  GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',

  GET_MORE_IMAGES: 'GET_MORE_IMAGES',
  GET_MORE_IMAGES_SUCCESS: 'GET_MORE_IMAGES_SUCCESS',
  GET_MORE_IMAGES_FAILURE: 'GET_MORE_IMAGES_FAILURE',
};

export default ActionTypes;
